data_location: /home/theau/transformers_instability/data_and_tokenizers
train_data_location: train/train_data.json
test_data_location: valid/test_data.json
dataset_name: wikitext # wikitext | openwebtext
dataset_config_name: wikitext-103-raw-v1 # wikitext-103-raw-v1 | plain_text
validation_split_percentage: 10 # percentage of full dataset for validation set
tokenizer_name: null
use_slow_tokenizer: False
block_size: 128 #null
debug_set: False
train_debug_set_location: train/train_debug_set.json
test_debug_set_location: valid/test_debug_set.json