preprocessing_num_workers: null
per_device_eval_batch_size: 4  # 32
per_device_train_batch_size: 4  # 32
weight_decay: 0.0
learning_rate: 1.e-2
gradient_accumulation_steps: 1
num_train_epochs: 3
max_train_steps: null
lr_scheduler_type: linear
num_warmup_steps: 10  # 5e3