project_name: transformers_instability_no_trainer
run_name: "openwebtext"
overwrite_cache: False
checkpointing_steps: 100
with_tracking: True
output_dir: null #checkpoints
report_to: wandb
seed: 0
spike_threshold: 10
additional_tags: null